// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/anime.proto

package animepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAnimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnimeRequest) Reset() {
	*x = GetAnimeRequest{}
	mi := &file_proto_anime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnimeRequest) ProtoMessage() {}

func (x *GetAnimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnimeRequest.ProtoReflect.Descriptor instead.
func (*GetAnimeRequest) Descriptor() ([]byte, []int) {
	return file_proto_anime_proto_rawDescGZIP(), []int{0}
}

func (x *GetAnimeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AnimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Synopsis      string                 `protobuf:"bytes,3,opt,name=synopsis,proto3" json:"synopsis,omitempty"`
	MediaType     string                 `protobuf:"bytes,4,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	NumEpisodes   int32                  `protobuf:"varint,6,opt,name=num_episodes,json=numEpisodes,proto3" json:"num_episodes,omitempty"`
	StartDate     string                 `protobuf:"bytes,7,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,8,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	MeanScore     float64                `protobuf:"fixed64,9,opt,name=mean_score,json=meanScore,proto3" json:"mean_score,omitempty"`
	Rank          int32                  `protobuf:"varint,10,opt,name=rank,proto3" json:"rank,omitempty"`
	Popularity    int32                  `protobuf:"varint,11,opt,name=popularity,proto3" json:"popularity,omitempty"`
	Rating        string                 `protobuf:"bytes,12,opt,name=rating,proto3" json:"rating,omitempty"`
	Genres        []*Genre               `protobuf:"bytes,13,rep,name=genres,proto3" json:"genres,omitempty"`
	Studios       []*Studio              `protobuf:"bytes,14,rep,name=studios,proto3" json:"studios,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnimeResponse) Reset() {
	*x = AnimeResponse{}
	mi := &file_proto_anime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimeResponse) ProtoMessage() {}

func (x *AnimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimeResponse.ProtoReflect.Descriptor instead.
func (*AnimeResponse) Descriptor() ([]byte, []int) {
	return file_proto_anime_proto_rawDescGZIP(), []int{1}
}

func (x *AnimeResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AnimeResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AnimeResponse) GetSynopsis() string {
	if x != nil {
		return x.Synopsis
	}
	return ""
}

func (x *AnimeResponse) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *AnimeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AnimeResponse) GetNumEpisodes() int32 {
	if x != nil {
		return x.NumEpisodes
	}
	return 0
}

func (x *AnimeResponse) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *AnimeResponse) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *AnimeResponse) GetMeanScore() float64 {
	if x != nil {
		return x.MeanScore
	}
	return 0
}

func (x *AnimeResponse) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *AnimeResponse) GetPopularity() int32 {
	if x != nil {
		return x.Popularity
	}
	return 0
}

func (x *AnimeResponse) GetRating() string {
	if x != nil {
		return x.Rating
	}
	return ""
}

func (x *AnimeResponse) GetGenres() []*Genre {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *AnimeResponse) GetStudios() []*Studio {
	if x != nil {
		return x.Studios
	}
	return nil
}

type Genre struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Genre) Reset() {
	*x = Genre{}
	mi := &file_proto_anime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Genre) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Genre) ProtoMessage() {}

func (x *Genre) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Genre.ProtoReflect.Descriptor instead.
func (*Genre) Descriptor() ([]byte, []int) {
	return file_proto_anime_proto_rawDescGZIP(), []int{2}
}

func (x *Genre) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Genre) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Studio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Studio) Reset() {
	*x = Studio{}
	mi := &file_proto_anime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Studio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Studio) ProtoMessage() {}

func (x *Studio) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Studio.ProtoReflect.Descriptor instead.
func (*Studio) Descriptor() ([]byte, []int) {
	return file_proto_anime_proto_rawDescGZIP(), []int{3}
}

func (x *Studio) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Studio) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SearchAnimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Q             string                 `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`
	Genre         string                 `protobuf:"bytes,2,opt,name=genre,proto3" json:"genre,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	MediaType     string                 `protobuf:"bytes,4,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchAnimeRequest) Reset() {
	*x = SearchAnimeRequest{}
	mi := &file_proto_anime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchAnimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAnimeRequest) ProtoMessage() {}

func (x *SearchAnimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAnimeRequest.ProtoReflect.Descriptor instead.
func (*SearchAnimeRequest) Descriptor() ([]byte, []int) {
	return file_proto_anime_proto_rawDescGZIP(), []int{4}
}

func (x *SearchAnimeRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *SearchAnimeRequest) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *SearchAnimeRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SearchAnimeRequest) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

type SearchAnimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*AnimeResponse       `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchAnimeResponse) Reset() {
	*x = SearchAnimeResponse{}
	mi := &file_proto_anime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchAnimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAnimeResponse) ProtoMessage() {}

func (x *SearchAnimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAnimeResponse.ProtoReflect.Descriptor instead.
func (*SearchAnimeResponse) Descriptor() ([]byte, []int) {
	return file_proto_anime_proto_rawDescGZIP(), []int{5}
}

func (x *SearchAnimeResponse) GetData() []*AnimeResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	MediaType     string                 `protobuf:"bytes,2,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Sort          string                 `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	MinScore      int32                  `protobuf:"varint,4,opt,name=min_score,json=minScore,proto3" json:"min_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListRequest) Reset() {
	*x = GetListRequest{}
	mi := &file_proto_anime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListRequest) ProtoMessage() {}

func (x *GetListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListRequest.ProtoReflect.Descriptor instead.
func (*GetListRequest) Descriptor() ([]byte, []int) {
	return file_proto_anime_proto_rawDescGZIP(), []int{6}
}

func (x *GetListRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetListRequest) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *GetListRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *GetListRequest) GetMinScore() int32 {
	if x != nil {
		return x.MinScore
	}
	return 0
}

type GetListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data          []*AnimeResponse       `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListResponse) Reset() {
	*x = GetListResponse{}
	mi := &file_proto_anime_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListResponse) ProtoMessage() {}

func (x *GetListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anime_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListResponse.ProtoReflect.Descriptor instead.
func (*GetListResponse) Descriptor() ([]byte, []int) {
	return file_proto_anime_proto_rawDescGZIP(), []int{7}
}

func (x *GetListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetListResponse) GetData() []*AnimeResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_anime_proto protoreflect.FileDescriptor

const file_proto_anime_proto_rawDesc = "" +
	"\n" +
	"\x11proto/anime.proto\x12\x05anime\"!\n" +
	"\x0fGetAnimeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x9f\x03\n" +
	"\rAnimeResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bsynopsis\x18\x03 \x01(\tR\bsynopsis\x12\x1d\n" +
	"\n" +
	"media_type\x18\x04 \x01(\tR\tmediaType\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12!\n" +
	"\fnum_episodes\x18\x06 \x01(\x05R\vnumEpisodes\x12\x1d\n" +
	"\n" +
	"start_date\x18\a \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\b \x01(\tR\aendDate\x12\x1d\n" +
	"\n" +
	"mean_score\x18\t \x01(\x01R\tmeanScore\x12\x12\n" +
	"\x04rank\x18\n" +
	" \x01(\x05R\x04rank\x12\x1e\n" +
	"\n" +
	"popularity\x18\v \x01(\x05R\n" +
	"popularity\x12\x16\n" +
	"\x06rating\x18\f \x01(\tR\x06rating\x12$\n" +
	"\x06genres\x18\r \x03(\v2\f.anime.GenreR\x06genres\x12'\n" +
	"\astudios\x18\x0e \x03(\v2\r.anime.StudioR\astudios\"+\n" +
	"\x05Genre\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\",\n" +
	"\x06Studio\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"o\n" +
	"\x12SearchAnimeRequest\x12\f\n" +
	"\x01q\x18\x01 \x01(\tR\x01q\x12\x14\n" +
	"\x05genre\x18\x02 \x01(\tR\x05genre\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"media_type\x18\x04 \x01(\tR\tmediaType\"?\n" +
	"\x13SearchAnimeResponse\x12(\n" +
	"\x04data\x18\x01 \x03(\v2\x14.anime.AnimeResponseR\x04data\"x\n" +
	"\x0eGetListRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"media_type\x18\x02 \x01(\tR\tmediaType\x12\x12\n" +
	"\x04sort\x18\x03 \x01(\tR\x04sort\x12\x1b\n" +
	"\tmin_score\x18\x04 \x01(\x05R\bminScore\"Q\n" +
	"\x0fGetListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12(\n" +
	"\x04data\x18\x02 \x03(\v2\x14.anime.AnimeResponseR\x04data2\xc3\x01\n" +
	"\fAnimeService\x128\n" +
	"\bGetAnime\x12\x16.anime.GetAnimeRequest\x1a\x14.anime.AnimeResponse\x12?\n" +
	"\x06Search\x12\x19.anime.SearchAnimeRequest\x1a\x1a.anime.SearchAnimeResponse\x128\n" +
	"\aGetList\x12\x15.anime.GetListRequest\x1a\x16.anime.GetListResponseB;Z9github.com/jyotil-raval/mal-updater/proto/animepb;animepbb\x06proto3"

var (
	file_proto_anime_proto_rawDescOnce sync.Once
	file_proto_anime_proto_rawDescData []byte
)

func file_proto_anime_proto_rawDescGZIP() []byte {
	file_proto_anime_proto_rawDescOnce.Do(func() {
		file_proto_anime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_anime_proto_rawDesc), len(file_proto_anime_proto_rawDesc)))
	})
	return file_proto_anime_proto_rawDescData
}

var file_proto_anime_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_anime_proto_goTypes = []any{
	(*GetAnimeRequest)(nil),     // 0: anime.GetAnimeRequest
	(*AnimeResponse)(nil),       // 1: anime.AnimeResponse
	(*Genre)(nil),               // 2: anime.Genre
	(*Studio)(nil),              // 3: anime.Studio
	(*SearchAnimeRequest)(nil),  // 4: anime.SearchAnimeRequest
	(*SearchAnimeResponse)(nil), // 5: anime.SearchAnimeResponse
	(*GetListRequest)(nil),      // 6: anime.GetListRequest
	(*GetListResponse)(nil),     // 7: anime.GetListResponse
}
var file_proto_anime_proto_depIdxs = []int32{
	2, // 0: anime.AnimeResponse.genres:type_name -> anime.Genre
	3, // 1: anime.AnimeResponse.studios:type_name -> anime.Studio
	1, // 2: anime.SearchAnimeResponse.data:type_name -> anime.AnimeResponse
	1, // 3: anime.GetListResponse.data:type_name -> anime.AnimeResponse
	0, // 4: anime.AnimeService.GetAnime:input_type -> anime.GetAnimeRequest
	4, // 5: anime.AnimeService.Search:input_type -> anime.SearchAnimeRequest
	6, // 6: anime.AnimeService.GetList:input_type -> anime.GetListRequest
	1, // 7: anime.AnimeService.GetAnime:output_type -> anime.AnimeResponse
	5, // 8: anime.AnimeService.Search:output_type -> anime.SearchAnimeResponse
	7, // 9: anime.AnimeService.GetList:output_type -> anime.GetListResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_anime_proto_init() }
func file_proto_anime_proto_init() {
	if File_proto_anime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_anime_proto_rawDesc), len(file_proto_anime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_anime_proto_goTypes,
		DependencyIndexes: file_proto_anime_proto_depIdxs,
		MessageInfos:      file_proto_anime_proto_msgTypes,
	}.Build()
	File_proto_anime_proto = out.File
	file_proto_anime_proto_goTypes = nil
	file_proto_anime_proto_depIdxs = nil
}
